a_im : [[1 / 6, 1 / 6], [1 / 3, 0, 1 / 3], [a, 0, b, c]]$
b_im : [a, 0, b, c]$

G(y):= G0 + G1 * y $
n: 4$
y[1]: y0$
for i: 2 thru n do (
  eq: y[i] = y0 + t * sum(a_im[i - 1][j] * G(y[j]), j, 1, i),
  y[i]: assoc(y[i], linsolve(eq, y[i])))$
y00: y0 + t * sum(b_im[i] * G(y[i]), i, 1, n)$

eq: 'diff('y, t) = G('y)$
sol: ic1(ode2(eq, 'y, 't), 't = 0, 'y = y0)$

res: y00 - rhs(sol);
res0: expand(taylor(res, 't, 0, 3));

coeff(res0, t, 0);
e: makelist(coeff(res0, t, i), i, 1, 2);
solve(e, [a, b]), c= 1/4;
